
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2014-2018 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("1.1.109")]
[assembly: AssemblyFileVersion("1.1.109")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("PetaJson")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2018, 10, 22, 22, 37, 53, DateTimeKind.Utc);
}
	