
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2014-2021 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("1.1.125")]
[assembly: AssemblyFileVersion("1.1.125")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("JsonKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2021, 1, 7, 5, 55, 9, DateTimeKind.Utc);
}
	